# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52f391050cf71379be977e82b9dbac6449822ac838db9eb40d664efaaf854a00988c044f0c6016b8acb1478ac2afca3accdefe65abaaed753ed660c8bb6ecacd

test:
  secret_key_base: 255a9ea9cd5936e2cbc9ee3f2ebcff0e853fd0914b0ff62f5c7215e979b30affb8f241236b81a5cb0c6b464904ad7d25ced46c6544f05677097e8fbc5d41dfe0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
